[package]
name = "rust-pubsub-example"
version = "0.1.0"
authors = ["x1- <viva008@gmail.com>"]

[dependencies]
base64 = "*"
google-pubsub1 = "*"
hyper = "^0.10"
hyper-rustls = "^0.6"
yup-oauth2 = "^1.0"

